server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
       ddl-auto: create