 spring:
  datasource: 
    url:  jdbc:h2:mem:mydb
    username: userName
    password: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
 