 spring:
  datasource: 
    url: jdbc:postgresql://database-1.cumvnewym5pd.us-east-2.rds.amazonaws.com:5432/postgres
    username: Kriley12
    password: Godsaveme24!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
 
