server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database-1.cumvnewym5pd.us-east-2.rds.amazonaws.com:5432/postgres
    username: Kriley12
    password: Godsaveme24!
  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create